language: java
jdk:
- oraclejdk8
sudo: required
service:
- docker
cache:
  directories:
  - "$HOME/.m2"
before_cache:
- rm -rf $HOME/.m2/repository
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: "BsTupfxlx5xr5OzxBu7pnlu+rLbOKu569k5F9Kq8ZcV3sFU3VXg7tjoHlJjNcwsjVwT+PIQi9t+weWl8omLhpDf4g0c+g7J9ffCl+orgio/7hxZ89q0UNtImPcDT5oVzK81W2n7xotxoK6y0PA7wSWt5ktsgRMsADA8gfVBrNJHbkud4VnSZWo9FYfBh6o0JrNrz/lgpkTebASNX6NfPVo3H3sruqC0jxG/hQAlZv9GkszbSNbowLMZJ5u0aZ2epcWVFUYDDtwhMhSD+hrE1T4LNaAdmBvNi/SB6zsQU/RRDM2glUFJl9+SMkQHUBPsO9WCxOITj1ZbYRBZiYc2GQdfea3VKXcdyYYawqIOCNm++1JDuUAyRguqGUHqNxxItVZFsmMu7DfYhrOqGdpS2fhOPY6XIFo9RPfKxoP9WU7VMKZZVmJcC0H7Z0H+CmuPHK43JnQ82ivwjvOn5V5viILEtloLARUl/irIMSk9+vfyMG6Dp6lU2mjwfQ9rSojixZ5XsqaIaqFZQqvrwIsM9RK6dNx64nsr+3RzUg1lbX7UOXbsbh8figBh9wUL5AHg5dnKyrOXP1BEkINu6V8iZY4awM8SRF7fBaYRwdB/XuCFcRBQSJ5zoH0XdoHipTM2Ot+3aZQc7JtfuTfFc3yHN6ej73HQn0HHAQ+/PmmzgCv0=" # DOCKER_USER
  - secure: "okmQr8g/yKN1CEFwHm68hsCJwgABA16L6HXD37pV17MoAV/5s+kVL9uXTza6XK27xHjPbRkzaxgWY6UOJ/XIfH+xe4M9+rwUTFy75kXH5qt6UazNMvm3PPtKQJTcQpSZ7HeGLhKJqBelNu2wUAO0OizE6GOCp0GlQbRzib/OzfYO27Xsk+1oPQ26cK8jpYeeV60L4JO8OhBeBxnLBP08D9Tf2osWAJLlf6Diejx/qW6RRBnkSCfXcFBGqbTEVxHtwtrZztU6q4DE6jEMHXz3pssQeV0hlinQB7dAKOO6+OewhzygH+k5CvxzgXeVzT8De/SnfRo2O2Q/xrn3QqvhSLHizPflMECm/E5qm9ngA3PfKJdG+3QQfGnSj4NfWKyo1d4/GXipk/6CkDpnMFkn9uVbzzRJnPRaWoEtCIs7Kmfzye49WU5D4Zn0fhugh3cy3IQ1rIIn8g3TdCv/hpY+5wl3czQrttPAJrASCp2tI2n1R3ZATasRjboxzmlsAGfo1A0qeJ642CGR8dAvphRJeLsLiqcj2WZ6/s9bDZh01C4yk4JCO1xh+iLKp30ZmidQg1JLJSjn0E+nNGN3NId/4eD7nWZOhxsBUk/R6viae5VsZMDMuie3+7+Z465RBXMG/Emln/OkLvcQKIUk4vVsJBWu2VsDQ5Fn5NxG4C9XBjM=" # DOCKER_PASS
  - secure: "r1ck7mQ2QgAQFuc3tTdSpAoKP+iFsaAPoNpAiZFOSqXF6CUlydXYPK/FHqr8buEx2/+FCrI8yXpLP9URT3j6qZYQHAmoLzOzYtftrMgvHkRV91dAI+2RjorJVeEpcDjE2RmkWf/J3xvM4pnmQS68WUEZHqUpfL+TurKwVoc//pv5s/slDINV+W+UGGoobfDnCiIz10hI9jNIoOnkluH5a7qTyLYz0XWnq3ADL6Nkx2QpWJ9cRIz5t/6w2XHesOC3eG8nt6PwsLaa0eEkf7Iq1zkjNPyMqNjOD7qkNXxlCB5jFzA/85bljbc2Cd7/WjcYsTtPn+HXESxMj2ztHyqa9LEqGqoMw3WTAn7nXmNxz9aC9BiXwR07Am1Je1jITeOSA44i4iyE2iX/faOj1aD+AZAmi8oD3yDvjHcSjK3v3TrnzgEJr3VIeOyBh1yR21V8ERRqxyxMbaXPPwG/cvP6DisqBJnh7DDT/UcaG+S/WHYZakOpVQkiHlWSbnBCXnD6dBj1iOHBUYyGCUkKeJiGKQKGVGjtQ9pfwQk0Af9xq+Xru2+x4Q6BwpsH9uaYR6l3wkJTOtW8et8pBkJY6m4y7127lko9BRHGaNClVKz9abaNhvkynMBxTsQDkcIuBlIAqZeMBgdCf30pN5xeq55igMJliYSc3SYyP7FrWjFg0hM=" # OSSRH_USER
  - secure: "lukzZ82+/aZQ56+TmMHWHqfqtekh4f4rnKRYYMaiZdx8pqS5Qvi+CKRzw5BR8YLLWYXP0+Ho9Kpkk48mOLxu41pLYR5w5ZRYU/85/aA+skyEXjJQXMm5y6LIs9TY+nPWBFvvtvP50NdvIFjaLD5aUhrRi7UNWG4AglqrV7b4wfzvG3R2AaK+4CLGDhNIoO5ehcyMqJsGKdxd2j62vbOTD1W8BzvtxPXr6YTM0VsYsDorqPUja8NB48o4jJMyqg6V+NYJHpm4z3vYFOALhCwo4YXogp1kw4qsignDy76S862puMd+aWmqHZGlVsqfC2clQgLxfRWi7F1igWhJu1i67g6hynitU8bXLK+y3uet/0LVHnZJ2sw6DPSbwzllgNc/tjQxb7PAKT7avLF12rp2Eq6xIFIH44cCau5bl44m0GJ4HmSrMS4pyOVS56kDWcBRoBTy8jfDc+JivAZ2urAZ5AKfy2aaDil2dK1XeKljp17zNF4QNn2pGRdxcWIBHi3/Bc+fK3O11nM8GiYOr1tR6w1aLV+IAlDO9gGN7leH2Ohqmt+30He5VRuLGSqGZVkK7gwkcJyDU1p0nostXG2QB90n/kjPlH5JZF6aMJrN1cYlcnFgrH5qJ1Txoh9aV+BP8kPCOBnn6o9LI0OwxzcEE222lT7F69vJvfyLHH/jBmY=" # OSSRH_PASS
  - secure: "gsPgkaqY+2pn6fE9rCABdQ896sgzo/Ypax9cQ8+YHt1ueSvf0irFYYae1HPS9+U011rpR8N/ICtF3ujTrUpfpBGL8lHSdCoH6e+nIzRt292/WcnRszyC91GyHM1MS0tBsTLbSet+xx3NqwE41x0ZTaYuokIIfb6w5CJvKJb+W0LpEHqMA6ZK3lI7oc2HZku7krGfziZesFukezuNuuVpj22d/9SjhHTV7+IEC0noD13330Cw/90Ldpr9HNGzu0dgpMbUU2VfP/f4ZZYlSYqQxsah3BfwH3XmvI9Am/FbGaZA2L0YjVS+Fq9rUHOq7dw9IfcDOyHPLKQ8PxlrfIhXBHEBnw5jspaumN49WSqbDm8RuGKrXS7n4PXIK4SRafeFdIhIMpGK17fbQHKuMkUIic5E9lMaZ/cgNdW2WTu+GoPZ2Hu8cgygm+xl11oPUId5/kg/Fng0Dp4bmh+e6h80HHVBHQyzlQ2OzbWmFCiKRqLQklFcMnkSKNnwUQSpv3zW6J4v92w1Ur1eqKU0UxbMxx7YZn6aynDzUCegHYWoCkAtAFxFKoNC4ymbB2uHLHMKiS/H3PrR3K2zg3XY56ktNJXYcvrO+lWtDApMNQYLHlWZ+W5hI2bEPuxSeSVn1zccLNqvPso87YsfM5LJdgjfjtaOAGHgLezFQJucmzRIcZ0=" # GPG_KEY_NAME
  - secure: "KraS/afE2uP9N3q5J/N6L39ANQWotrIXGWzBsG83UeRf9P96ODHI608ahlYv/YPg+xc+QdJ+d7r5Za62bOgJp+PRSbXVzk+R6WwPV7KlB3jpeHUV9Q36+nrV7ojgJicgXI6g47DNdPc2/Z+cX15dZCEGe8ZyF6E/X10lBxnB7UkaDBJh9P9mx2KKEXZQ7YK0TzTSZImHKMamNnlQBGKVEAi7XL0comx/O9OSeCvY6Yqao0X4V90w086222rKAXfwu8vCqYcwILUc6lVFpJcR8AMCwqJLE7nMWhV6brKRr2Q7NNQcx6QUo4sPsp6DhpCv/8oEy/xsSGdKmxRR4X+311ZtwE5tHWS97c4BYWINgFUvB+6FEa1H/N4k6iiWJrtSwDq+PEFim1DccYyoH1CZs4IjFHSRK7akgb/q4+uyBXLSOwpzvVnTYyE1Wes908nm01qiRt94viy2AaDxq+dbcyxRs0Kum54nme4a9kUrTJv56Oivkr70Ykb5fXvsTVb7S4+OlmSsEHAkAX2PDAEeQhK9vwm0v2XE/s9/5tpMk9MdwA4pGgK236doFfqZzTRYpfg7OVzlWVSR3eB1DvR1vwLExD87U8jNwwdbKA6Kotcevae1pNIVCBt92Wd/RCxczd09Otl14IVwCCRl00OJUCyHh2yEasLgSVCFaOxjRFI=" # GPG_PASSPHRASE
stages:
- name: deploy
- name: build
- name: test
- name: docker
jobs:
  include:
  - stage: deploy
    before_script:
    - "gpg --fast-import ./.travis/codesigning.asc"
    script: "./mvnw deploy -DskipTests=true -Dtravis --settings ./.travis/deploy-settings.xml"
  - stage: build
    script: "./mvnw clean package -Dmaven.test.skip=true --settings ./.travis/deploy-settings.xml"
  - stage: test
    before_script:
    - sudo touch /var/log/hesperides.log
    - sudo chown travis /var/log/hesperides.log
    script: "./mvnw test"
  - stage: test
    env:
    - INTEGRATION TEST
    script: "./mvnw -pl tests/integration verify -P integration-test"
  - stage: docker
    if: type != pull_request AND fork = false
    script: "./.travis/docker_build_push.sh"

